site_name: 'Awesome Software Language Engineering'
site_url: 'https://manuelleduc.github.io/awesome-software-language-engineering/'
site_description: 'A curated list of software language engineering tools, frameworks and books.'
site_author: 'Manuel Leduc'
repo_name: 'manuelleduc/awesome-software-language-engineering/'
repo_url: 'https://github.com/manuelleduc/awesome-software-language-engineering/'
theme: 'material'
extra:
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'pink'
  social:
    - type: 'github'
      link: 'https://github.com/manuelleduc'
    - type: 'twitter'
      link: 'https://twitter.com/manuel_leduc'
extra_css:
  - css/extra.css
markdown_extensions:
    - toc:
